[package]
name = "client"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
anyhow = "1.0.45"
cc = { version = "1.0", features = ["parallel"] }
cmake = "0.1"
dunce = "1.0.2"